apiVersion: v1
kind: ConfigMap
metadata:
  name: kargo-helm-demo-content
data:
  index.html: |-
    <!DOCTYPE html>
    <html>
    <head>
    <title>{{ .Values.env }}</title>
    </head>
    <body>
    hello world
    <h1>{{ .Values.env }}</h1>

    </body>
    </html>