apiVersion: v1
kind: Service
metadata:
  name: kargo-helm-demo
spec:
  type: NodePort
  selector:
    app: kargo-helm-demo
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 80
    nodePort: {{ .Values.nodePort }}
